<!doctype html>
<!-- This site was created with Hugo Blox. https://hugoblox.com -->
<!-- Last Published: April 12, 2025 --><html lang="en-us" dir="ltr"
      data-wc-theme-default="auto">
  
<head><script src="/livereload.js?mindelay=10&amp;v=2&amp;port=1313&amp;path=livereload" data-no-instant defer></script>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="generator" content="Hugo Blox Builder 0.3.1" />

  
  












  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Francis L. Huang" />

  
  
  
    
  
  <meta name="description" content="A primer on using IVs" />

  
  <link rel="alternate" hreflang="en-us" href="http://localhost:1313/post/iv/" />

  
  
  
  
    
    <link rel="stylesheet" href="/css/themes/blue.min.css" />
  

  
  
    
    <link href="/dist/wc.min.css" rel="stylesheet" />
  

  
  
  

  

  <script>
     
    window.hbb = {
       defaultTheme: document.documentElement.dataset.wcThemeDefault,
       setDarkTheme: () => {
        document.documentElement.classList.add("dark");
        document.documentElement.style.colorScheme = "dark";
      },
       setLightTheme: () => {
        document.documentElement.classList.remove("dark");
        document.documentElement.style.colorScheme = "light";
      }
    }

    console.debug(`Default Hugo Blox Builder theme is ${window.hbb.defaultTheme}`);

    if ("wc-color-theme" in localStorage) {
      localStorage.getItem("wc-color-theme") === "dark" ? window.hbb.setDarkTheme() : window.hbb.setLightTheme();
    } else {
      window.hbb.defaultTheme === "dark" ? window.hbb.setDarkTheme() : window.hbb.setLightTheme();
      if (window.hbb.defaultTheme === "system") {
        window.matchMedia("(prefers-color-scheme: dark)").matches ? window.hbb.setDarkTheme() : window.hbb.setLightTheme();
      }
    }
  </script>

  <script>
    
    document.addEventListener('DOMContentLoaded', function () {
      
      let checkboxes = document.querySelectorAll('li input[type=\'checkbox\'][disabled]');
      checkboxes.forEach(e => {
        e.parentElement.parentElement.classList.add('task-list');
      });

      
      const liNodes = document.querySelectorAll('.task-list li');
      liNodes.forEach(nodes => {
        let textNodes = Array.from(nodes.childNodes).filter(node => node.nodeType === 3 && node.textContent.trim().length > 1);
        if (textNodes.length > 0) {
          const span = document.createElement('label');
          textNodes[0].after(span);  
          span.appendChild(nodes.querySelector('input[type=\'checkbox\']'));
          span.appendChild(textNodes[0]);
        }
      });
    });
  </script>

  
  
  




































  
  

  
  <link rel="icon" type="image/png" href="/media/icon_hu_3a05525e284cb133.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hu_f701646b16bb8941.png" />

  <link rel="canonical" href="http://localhost:1313/post/iv/" />

  
  
  
  
  
  
  
  
    
    
  
  

  
  
    
    
  
  <meta property="twitter:card" content="summary" />
  
    <meta property="twitter:site" content="@flhuang" />
    <meta property="twitter:creator" content="@flhuang" />
  
  <meta property="og:site_name" content="FLH Website" />
  <meta property="og:url" content="http://localhost:1313/post/iv/" />
  <meta property="og:title" content="🎉 Understanding instrumental variables | FLH Website" />
  <meta property="og:description" content="A primer on using IVs" /><meta property="og:image" content="http://localhost:1313/media/icon_hu_7c4bcaa7031a3f50.png" />
    <meta property="twitter:image" content="http://localhost:1313/media/icon_hu_7c4bcaa7031a3f50.png" /><meta property="og:locale" content="en-us" />
  
    
      <meta
        property="article:published_time"
        content="2018-06-27T00:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2018-06-27T00:00:00&#43;00:00">
  

  



  


  <title>🎉 Understanding instrumental variables | FLH Website</title>

  
  
  
  
  
    
    
  
  
  <style>
    @font-face {
      font-family: 'Inter var';
      font-style: normal;
      font-weight: 100 900;
      font-display: swap;
      src: url(/dist/font/Inter.var.woff2) format(woff2);
    }
  </style>

  

  
  


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
      
      
    
      
      
        
        
          
        
          
        
          
        
          
        
          
        
        
        
      
    
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  







<link type="text/css" rel="stylesheet" href="/dist/pagefind/pagefind-ui.be766eb419317a14ec769d216e9779bfe8f3737c80e780f4ba0dafb57a41a482.css" integrity="sha256-vnZutBkxehTsdp0hbpd5v&#43;jzc3yA54D0ug2vtXpBpII=" />


<script src="/dist/pagefind/pagefind-ui.87693d7c6f2b3b347ce359d0ede762c033419f0a32b22ce508c335a81d841f1b.js" integrity="sha256-h2k9fG8rOzR841nQ7ediwDNBnwoysizlCMM1qB2EHxs="></script>


<script>window.hbb.pagefind = {"baseUrl":"/"};</script>

<style>
  html.dark {
    --pagefind-ui-primary: #eeeeee;
    --pagefind-ui-text: #eeeeee;
    --pagefind-ui-background: #152028;
    --pagefind-ui-border: #152028;
    --pagefind-ui-tag: #152028;
  }
</style>

<script>
  window.addEventListener('DOMContentLoaded', (event) => {
    new PagefindUI({
      element: "#search",
      showSubResults: true,
      baseUrl: window.hbb.pagefind.baseUrl,
      bundlePath: window.hbb.pagefind.baseUrl + "pagefind/",
    });
  });
  document.addEventListener('DOMContentLoaded', () => {
    let element = document.getElementById('search');
    let trigger = document.getElementById('search_toggle');

    if (trigger) {
      trigger.addEventListener('click', () => {
        element.classList.toggle('hidden');
        element.querySelector("input").value = ""
        element.querySelector("input").focus()

        if (!element.classList.contains('hidden')) {
          let clear_trigger = document.querySelector('.pagefind-ui__search-clear');

          if (clear_trigger && !clear_trigger.hasAttribute('listenerOnClick')) {
            clear_trigger.setAttribute('listenerOnClick', 'true');

            clear_trigger.addEventListener('click', () => {
              element.classList.toggle('hidden');
            });
          }
        }

      });
    }
  });
</script>










  
  
  <link type="text/css" rel="stylesheet" href="/dist/lib/katex/katex.min.505d5f829022bb7b4f24dfee0aa1141cd7bba67afe411d1240335f820960b5c3.css" integrity="sha256-UF1fgpAiu3tPJN/uCqEUHNe7pnr&#43;QR0SQDNfgglgtcM=" />
  
  
  <script defer src="/dist/lib/katex/katex.min.dc84b296ec3e884de093158f760fd9d45b6c7abe58b5381557f4e138f46a58ae.js" integrity="sha256-3ISyluw&#43;iE3gkxWPdg/Z1Ftser5YtTgVV/ThOPRqWK4="></script>
  
  
  
  
  <script defer src="/js/katex-renderer.6579ec9683211cfb952064aedf3a3baea5eeb17a061775b32b70917474637c80.js" integrity="sha256-ZXnsloMhHPuVIGSu3zo7rqXusXoGF3WzK3CRdHRjfIA="></script>
  
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  
    
  






  
  
  
  
  
  
  
  <script
    defer
    src="/js/hugo-blox-en.min.js"
    integrity=""
  ></script>

  
  








  
    
      
      <script async defer src="https://buttons.github.io/buttons.js"></script>

      
    
  




</head>

  <body class="dark:bg-hb-dark dark:text-white page-wrapper" id="top">
    <div id="page-bg"></div>
    <div class="page-header sticky top-0 z-30">
      
      
      
        
        
        
          <header id="site-header" class="header">
  <nav class="navbar px-3 flex justify-left">
    <div class="order-0 h-100">
      
      <a class="navbar-brand" href="/" title="FLH Website">
        Francis L. Huang
      </a>
    </div>
    
    <input id="nav-toggle" type="checkbox" class="hidden" />
    <label
      for="nav-toggle"
      class="order-3 cursor-pointer flex items-center lg:hidden text-dark dark:text-white lg:order-1">
      <svg id="show-button" class="h-6 fill-current block" viewBox="0 0 20 20">
        <title>Open Menu</title>
        <path d="M0 3h20v2H0V3z m0 6h20v2H0V9z m0 6h20v2H0V0z"></path>
      </svg>
      <svg id="hide-button" class="h-6 fill-current hidden" viewBox="0 0 20 20">
        <title>Close Menu</title>
        <polygon
          points="11 9 22 9 22 11 11 11 11 22 9 22 9 11 -2 11 -2 9 9 9 9 -2 11 -2"
          transform="rotate(45 10 10)"></polygon>
      </svg>
    </label>
    

    
    
    <ul
      id="nav-menu"
      class="navbar-nav order-3 hidden lg:flex w-full pb-6 lg:order-1 lg:w-auto lg:space-x-2 lg:pb-0 xl:space-x-8 justify-left
      ">
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/#talks"
        >Talks</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/#news"
        >Posts</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/MLMusingR/"
        >MLMusingR</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/projects/"
        >Projects</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/teaching/"
        >Teaching</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item">
        <a
          class="nav-link "
          
          href="/service/"
        >Service</a
        >
      </li>
      
      
      
      
      
      
      <li class="nav-item nav-dropdown group relative">
            <span
              class="nav-link 
                
                
                
              
                
                
                
               inline-flex items-center">
              Research
              <svg class="h-4 w-4 fill-current inline-block" viewBox="0 0 20 20">
                <path
                  d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
              </svg>
            </span>
        <ul
          class="nav-dropdown-list lg:group-hover:visible lg:group-hover:opacity-100">
          
          
          
          <li class="nav-dropdown-item">
            <a
              class="nav-dropdown-link "
              
              href="/#papers">
              Papers
            </a>
          </li>
          
          
          
          <li class="nav-dropdown-item">
            <a
              class="nav-dropdown-link "
              
              href="/r">
              R Packages
            </a>
          </li>
          
        </ul>
      </li>
      
      
      
    </ul>

    <div class="order-1 ml-auto flex items-center md:order-2 lg:ml-0">

      
      
      
      <button
        aria-label="search"
        class="text-black hover:text-primary  inline-block px-3 text-xl dark:text-white"
        id="search_toggle">
        <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512" fill="currentColor"><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
      </button>
      

      
      
      <div class="px-3 text-black hover:text-primary-700 dark:text-white dark:hover:text-primary-300
            [&.active]:font-bold [&.active]:text-black/90 dark:[&.active]:text-white">
        <button class="theme-toggle mt-1" accesskey="t" title="appearance">
          <svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
               fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
               stroke-linejoin="round" class="dark:hidden">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
          </svg>
          <svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24"
               fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
               stroke-linejoin="round" class=" dark:block [&:not(dark)]:hidden">
            <circle cx="12" cy="12" r="5"></circle>
            <line x1="12" y1="1" x2="12" y2="3"></line>
            <line x1="12" y1="21" x2="12" y2="23"></line>
            <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>
            <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>
            <line x1="1" y1="12" x2="3" y2="12"></line>
            <line x1="21" y1="12" x2="23" y2="12"></line>
            <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>
            <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>
          </svg>
        </button>
      </div>
      

      
      

      
      
    </div>
  </nav>
</header>


<div id="search" class="hidden p-3"></div>


        
      
    </div>
    <div class="page-body  my-10">
      





<div class="mx-auto flex max-w-screen-xl">
  



<aside class="hb-sidebar-container max-lg:[transform:translate3d(0,-100%,0)] lg:hidden xl:block">
  
  <div class="px-4 pt-4 lg:hidden">
    
    
  </div>
  <div class="hb-scrollbar lg:h-[calc(100vh-var(--navbar-height))]">
    <ul class="flex flex-col gap-1 lg:hidden">
      
      
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/"
    
  >Publications
        <span data-hb-sidebar-toggle>
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-[18px] min-w-[18px] rounded-sm p-0.5 hover:bg-gray-800/5 dark:hover:bg-gray-100/5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" class="origin-center transition-transform rtl:-rotate-180"></path></svg>
        </span>
    </a><div class="ltr:pr-0 overflow-hidden">
        <ul class="hb-sidebar-list"><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2025/lsa-weights/"
    
  >Reassessing weights in large-scale assessments and multilevel models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2025/cornell-behavioral-2025/"
    
  >Behavioral threat assessment and equity in exclusionary school discipline
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2025/huang-cluster-robust-2025/"
    
  >Cluster-robust standard errors with three-level data
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2025/cornell-referral-2025/"
    
  >Referral rates for school threat assessment
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/gregory-restorative-2025/"
    
  >Restorative justice conferences in elementary and secondary schools
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/jimerson-advancing-2024/"
    
  >Advancing diversity, equity, and inclusion in school psychology science and scholarship: Changing training and practice in the field of school psychology
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/chuang-potential-2022/"
    
  >Potential moderation across racial groups in perceptions of authoritative school climate and peer victimization and student engagement
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/huang-seasonality-2023/"
    
  >The seasonality of school climate
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/smith-school-2024/"
    
  >School bullying and gender minority youth: Victimization experiences and perceived prevalence
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/reinke-having-2024/"
    
  >Having a trusted adult in school: Concurrent and predictive relations with internalizing problems across development
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/eddy-positive-2024/"
    
  >Positive student-teacher relationships and exclusionary discipline practices
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/gregory-steadfast-2023/"
    
  >Steadfast implementation of restorative practices during the Covid-19 pandemic: A case study of consultancy and leadership in an elementary school
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/huang-replication-2024/"
    
  >Replication studies using secondary or nonexperimental datasets
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/huang-using-2024/"
    
  >Using plausible values when fitting multilevel models with large-scale assessment data using R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/gregory-adolescent-2024/"
    
  >Adolescent exposure to restorative practices and their perceptions of support, structure, and bullying in the school climate
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2025/stemmler-investigating-2024/"
    
  >Investigating the use of robust standard errors to account for two-way clustering in cross-classified data structures
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/huang-impact-2023/"
    
  >The impact of restorative practices on the use of out-of-school suspensions: Results from a cluster randomized controlled trial
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/woods-relationship-2023/"
    
  >The relationship between teacher stress and job satisfaction as moderated by coping
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/herman-usability-2023/"
    
  >Usability and social consequences of the early identification system as a universal screener for social, emotional, and behavioral risks.
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/huang-accounting-2023/"
    
  >Accounting for heteroskedasticity resulting from between-group differences in multilevel models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/wiedermann-advanced-2023/"
    
  >Advanced categorical data analysis in prevention science
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/cohen-school-2023/"
    
  >In-school and out-of-school suspension: Behavioral and psychological outcomes in a predominately black sample of middle school students
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/book/huang-practical-2023/"
    
  >Practical multilevel modeling using R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/maeng-teacher-2023/"
    
  >Teacher Perceptions of School Resource Officers and Associations with School Safety
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/huang-using-2023/"
    
  >Using robust standard errors for the analysis of binary outcomes with a small number of clusters
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/gregory-evaluation-2022/"
    
  >Evaluation of the whole school restorative practices project: One-year impact on discipline incidents
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/olsen-interaction-2022/"
    
  >Interaction of socioeconomic status and class relations on reading
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/crichlow-ball-student-2022/"
    
  >Student perceptions of school resource officers and threat reporting
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/reinke-examining-2022/"
    
  >Examining the validity of the Early Identification System – Student Version for screening in an elementary school sample
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/huang-alternatives-2022/"
    
  >Alternatives to logistic regression models in experimental studies
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/huang-analyzing-2022/"
    
  >Analyzing cross-sectionally clustered data using generalized estimating equations
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/eddy-evaluation-2022/"
    
  >Evaluation of a bibliotherapy-based stress intervention for teachers
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/huang-using-2022/"
    
  >Using cluster-robust standard errors when analyzing group-randomized trials with few clusters
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/herman-individual-2021/"
    
  >Individual and school predictors of teacher stress, coping, and wellness during the COVID-19 pandemic
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/olsen-association-2021/"
    
  >The association between student socioeconomic status and student–teacher relationships on math achievement
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/huang-does-2021/"
    
  >Does worrying matter? Priming and attitudes towards mask wearing in a midwestern state
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/stohlman-high-2021/"
    
  >High school graduation outcomes of student threat assessment
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test3/jimerson-advancing-2021/"
    
  >Advancing diversity, equity, and inclusion in school psychology: Be the change
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2022/herman-investigation-2021/"
    
  >An investigation of the psychometric properties of the Early Identification System–student report in a middle school sample
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2020/huang-authoritative-2021/"
    
  >Authoritative school climate and out-of-school suspensions: Results from a nationally-representative survey of 10th grade students
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2020/thompson-confirmatory-2021/"
    
  >Confirmatory factor structure and predictive validity of the Early Identification System—Student Report in a community sample of high school students
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/huang-teacher-2021/"
    
  >Teacher support for zero tolerance is associated with higher suspension rates and lower feelings of safety
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/maeng-student-2020/"
    
  >Student threat assessment as an alternative to exclusionary discipline
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/jiv/huang-role-2017/"
    
  >The role of the perceptions of school climate and teacher victimization by students
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2020/eddy-does-2020/"
    
  >Does teacher emotional exhaustion and efficacy predict student discipline sanctions?
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/huang-prior-2020/"
    
  >Prior problem behaviors do not account for the racial suspension gap
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2020/huang-manova-2020/"
    
  >MANOVA: A procedure whose time has passed?
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2020/huang-relationship-2020/"
    
  >The relationship between school disciplinary resolutions with school climate and attitudes toward school
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/prewett-student-2019/"
    
  >Student and teacher perceptions on student-teacher relationship quality: A middle school perspective
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2019/huang-investigation-2019/"
    
  >An investigation of the psychometric properties of the Early Identification System–Student Report
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/huang-school-2019/"
    
  >School teasing and bullying after the presidential election
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/burnette-school-2019/"
    
  >School threat assessment versus suicide assessment: Statewide prevalence and case characteristics
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/olsen-teacher-2019/"
    
  >Teacher job satisfaction by principal support and teacher cooperation: Results from the Schools and Staffing Survey
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2019/smith-understanding-2019/"
    
  >Understanding family–school engagement across and within elementary- and middle-school contexts
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-multilevel-2018-1/"
    
  >Multilevel modeling myths
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-relationship-2018/"
    
  >The relationship of school climate with out-of-school suspensions
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/ford-effect-2018/"
    
  >The effect of orthographic complexity on Spanish spelling in Grades 1–3
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/gregory-examination-2018/"
    
  >An examination of restorative interventions and racial equity in out-of-school suspensions
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-bullying-2018/"
    
  >Bullying involvement, teacher-student relationships, and psychosocial outcomes
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-black-2018/"
    
  >Do Black students misbehave more? Investigating the differential involvement hypothesis and out-of-school suspensions
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-multilevel-2018/"
    
  >Multilevel modeling and ordinary least squares regression:  How comparable are they?
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/cornell-racialethnic-2018/"
    
  >Racial/ethnic parity in disciplinary consequences using student threat assessment
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/jia-impact-2018/"
    
  >The impact of validity screening on associations between self-reports of bullying victimization and student outcomes
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-using-2018-1/"
    
  >Using cluster bootstrapping to analyze nested data with a few clusters
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-using-2018/"
    
  >Using instrumental variable estimation to evaluate randomized experiments with imperfect compliance
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/bullying/datta-toxicity-2017/"
    
  >The toxicity of bullying by teachers and other school staff
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/cornell-student-2017/"
    
  >Student Threat Assessment as a Standard School Safety Practice: Results From a Statewide Implementation Study.
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/cornell-student-2017/"
    
  >Student Threat Assessment as a Standard School Safety Practice: Results From a Statewide Implementation Study.
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/huang-student-2017/"
    
  >Student attitudes and behaviors as explanations for the Black-White suspension gap
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/konold-racialethnic-2017/"
    
  >Racial/ethnic differences in perceptions of school climate and its association with student engagement and peer aggression
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/huang-question-2016/"
    
  >Question order affects the measurement of bullying victimization among middle school students
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/bullying/datta-aggressive-2016/"
    
  >Aggressive attitudes and prevalence of bullying bystander behavior in middle school
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/bullying/millspaugh-prevalence-2015/"
    
  >Prevalence of aggressive attitudes and willingness to report threats in middle school
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/cornell-school-2015/"
    
  >School counselor use of peer nominations to identify victims of bullying
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/rubie-davies-successive-2014/"
    
  >Successive teacher expectation effects across the early school years
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/gregory-it-2013/"
    
  >It takes a village: The effects of 10th grade college-going expectations of students, parents, and teachers four years later
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/test2/huang-differential-2012/"
    
  >The differential effects of preschool: Evidence from Virginia
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-is-2009/"
    
  >Is experience the best teacher? A multilevel analysis of teacher characteristics and student achievement in low performing schools
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/publication/journal-article/2018/huang-corruption-2008/"
    
  >Corruption and educational outcomes: Two steps forward, one step back
    </a>
              
            </li></ul>
      </div></li>
        <li class="open"><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/"
    
  >Posts
        <span data-hb-sidebar-toggle>
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-[18px] min-w-[18px] rounded-sm p-0.5 hover:bg-gray-800/5 dark:hover:bg-gray-100/5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" class="origin-center transition-transform rtl:-rotate-180"></path></svg>
        </span>
    </a><div class="ltr:pr-0 overflow-hidden">
        <ul class="hb-sidebar-list"><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/weights_2025/"
    
  >Weights with Multilevel Models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/jobs-2025/"
    
  >🎉 Job postings 2024-2025
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/pca-image/"
    
  >Fun with PCA using Images
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/2024_lsa/"
    
  >Selecting the proper weights in LSAs with multilevel models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/pv3/"
    
  >Using Plausible Values with Multilevel Models Using R (update)
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/pv/"
    
  >Using Plausible Values with Multilevel Models Using R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/jobs-2024/"
    
  >🎉 Job postings 2023-2024
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/gd_example/"
    
  >Gradient descent example 1
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/logreg_matrix/"
    
  >🖩 Logistic regression with matrices
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/residuals_mlm/"
    
  >Residuals with Multilevel Models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/jobs-2023/"
    
  >🎉 Job postings 2022-2023
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/residuals/"
    
  >Fun with residuals
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/mi_pt3/"
    
  >Using FIML in R for Multilevel Data
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/2022_cr2/"
    
  >Robust standard errors in mixed models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/logistic-regression-fisher-scoring/"
    
  >Logistic regression from scratch (Newton Raphson and Fisher Scoring)
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/likelihood_2022/"
    
  >Using REML and ML for estimation
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/extracting-v-matrix/"
    
  >Extracting the V matrix for MLMs
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/gee/"
    
  >🎉 Analyzing clustered data using GEEs
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/ml/"
    
  >🎉 Using maximum likelihood
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/compare/"
    
  >🎉 Comparing coefficients across logistic regression models
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/prior-problem-behavior-and-suspensions-a-replication/"
    
  >Prior problem behavior and suspensions: A replication
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/mdata/"
    
  >🎉 Using FIML and MI in R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/applied/"
    
  >🎉 Applied example for alternatives to logistic regression
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/pca_2020/"
    
  >🎉 Principal Components Analysis using R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/centering/"
    
  >🎉 Why does centering reduce multicollinearity?
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/poisson-and-negative-binomial-regression-using-r/"
    
  >Poisson and Negative Binomial Regression using R
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/mlcfa/"
    
  >Multilevel CFA (MLCFA) in R, part 2
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/sim2data/"
    
  >🎉 Simulating two level data
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/2018-06-16-difference-between-variance-covariance-and-correlation-matrix/"
    
  >🧠 Difference between correlation and covariance matrices
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/iv2/2018-08-17-instrumental-variables-within-a-sem-framework/"
    
  >Instrumental variables within an SEM framework
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/se/"
    
  >🎉 Class Example- Standard Errors Too Small
    </a>
              
            </li><li class="flex flex-col open"><a
    class="hb-sidebar-custom-link
      sidebar-active-item bg-primary-100 font-semibold text-primary-800 dark:bg-primary-300 dark:text-primary-900"
    href="/post/iv/"
    
  >🎉 Understanding instrumental variables
    </a>
  
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/post/ovb/"
    
  >Omitted Variable Bias (OVB) Example
    </a>
              
            </li></ul>
      </div></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/mlmusingr/"
    
  >
    </a></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/r/"
    
  >
    </a></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/service/"
    
  >
    </a></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/project/"
    
  >Projects
        <span data-hb-sidebar-toggle>
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-[18px] min-w-[18px] rounded-sm p-0.5 hover:bg-gray-800/5 dark:hover:bg-gray-100/5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" class="origin-center transition-transform rtl:-rotate-180"></path></svg>
        </span>
    </a><div class="ltr:pr-0 overflow-hidden">
        <ul class="hb-sidebar-list"><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/project/uva/"
    
  >Youth Violence Project @ UVA
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/project/av/"
    
  >MO Prison Transformation Project
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/project/mpsi/"
    
  >Missouri Prevention Science Institute
    </a>
              
            </li></ul>
      </div></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/projects/"
    
  >Projects
    </a></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/event/"
    
  >Recent &amp; Upcoming Talks
        <span data-hb-sidebar-toggle>
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-[18px] min-w-[18px] rounded-sm p-0.5 hover:bg-gray-800/5 dark:hover:bg-gray-100/5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" class="origin-center transition-transform rtl:-rotate-180"></path></svg>
        </span>
    </a><div class="ltr:pr-0 overflow-hidden">
        <ul class="hb-sidebar-list"><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/event/example/"
    
  >Replication studies using secondary and nonexperimental datasets
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/event/mlm_ph/"
    
  >Multilevel Modeling with Large-Scale International Databases Using HLM (Philadelphia)
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/event/korea_23/"
    
  >Using cluster robust standard errors to analyze nested data with a few clusters (Korea)
    </a>
              
            </li></ul>
      </div></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/"
    
  >Teaching
        <span data-hb-sidebar-toggle>
            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-[18px] min-w-[18px] rounded-sm p-0.5 hover:bg-gray-800/5 dark:hover:bg-gray-100/5"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" class="origin-center transition-transform rtl:-rotate-180"></path></svg>
        </span>
    </a><div class="ltr:pr-0 overflow-hidden">
        <ul class="hb-sidebar-list"><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/dm/"
    
  >Data Management (using R)
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/mcsim/"
    
  >Monte Carlo Simulation
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/mlm/"
    
  >Multilevel Modeling
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/eval/"
    
  >Program Evaluation
    </a>
              
            </li><li class="flex flex-col "><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/teaching/quantfound/"
    
  >Quantitative Foundations
    </a>
              
            </li></ul>
      </div></li>
        <li class=""><a
    class="hb-sidebar-custom-link
      text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-300 dark:hover:bg-primary-800 dark:hover:text-gray-50"
    href="/experience/"
    
  >Experience
    </a></li>
    </ul>

    <div class="max-xl:hidden h-0 w-64 shrink-0"></div></div>

</aside>
  

<nav class="hb-toc order-last hidden w-64 shrink-0 xl:block print:hidden px-4" aria-label="table of contents">
  











  <div class="hb-scrollbar text-sm [hyphens:auto] sticky top-16 overflow-y-auto pr-4 pt-6 max-h-[calc(100vh-var(--navbar-height)-env(safe-area-inset-bottom))] -mr-4 rtl:-ml-4">

  
  
    
    
  



    












  </div>
  </nav>


  <article class="w-full break-words flex min-h-[calc(100vh-var(--navbar-height))] min-w-0 justify-center pb-8 pr-[calc(env(safe-area-inset-right)-1.5rem)]">
    <main class="w-full min-w-0 max-w-6xl px-6 pt-4 md:px-12">

      
      <div class="mb-4">
        <div class="mt-1.5 flex items-center gap-1 overflow-hidden text-sm text-gray-500 dark:text-gray-400">
      <div class="whitespace-nowrap transition-colors min-w-[24px] overflow-hidden text-ellipsis hover:text-gray-900 dark:hover:text-gray-100">
        <a href="http://localhost:1313/post/">Posts</a>
      </div><svg class="w-3.5 shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m8.25 4.5l7.5 7.5l-7.5 7.5"/></svg><div class="whitespace-nowrap font-medium text-gray-700 dark:text-gray-100">🎉 Understanding instrumental variables</div>
</div>

      </div>
      

      <h1 class="mt-2 text-4xl font-bold tracking-tight text-slate-900 dark:text-slate-100">🎉 Understanding instrumental variables</h1>

      <div class="mt-4 mb-16">
      <div class="text-gray-500 dark:text-gray-300 text-sm flex items-center flex-wrap gap-y-2"><span class="mr-1">Jun 27, 2018</span><span class="mx-1">·</span>
        
          
          
          <div class="group inline-flex items-center text-current gap-x-1.5 mx-1">
            
            
            <img src="/author/francis-l.-huang/avatar_hu_332976a1b81beb6b.webp" alt="Francis L. Huang" class="inline-block h-4 w-4 rounded-full border border-current" loading="lazy" />
            
            <div >Francis L. Huang</div>
          </div>
          
        

        
        <span class="mx-1">·</span>
        <span class="mx-1">
          13 min read
        </span>
        
        </div>

        <div class="mt-3">
          





        </div>
      </div>



      
      
      

      
      

      <div class="prose prose-slate lg:prose-xl dark:prose-invert">
        <div id="instrumental-variables-itt-and-tot" class="section level2">
<h2>Instrumental variables, ITT, and TOT</h2>
<p>Based on:</p>
<p>Angrist, J. D. (2006). Instrumental variables methods in experimental criminological research: what, why and how. <em>Journal of Experimental Criminology</em>, 2, 23-44. <a href="https://doi.org/10.1007/s11292-005-5126-x" class="uri">https://doi.org/10.1007/s11292-005-5126-x</a></p>
<p>Evaluation of the Minneapolis Domestic Violence Experiment (MDVE): Evaluated the police response to domestic violence reports. Experiment conducted in 1981-82 by Lawrence Sherman and Richard Berk. Police may be reluctant to get involved for various reasons (e.g., might be viewed as a private matter, may not want to get involved).</p>
<p>Design applied only to simple misdemenors where both suspect and victim were present when the police arrived. Only included cases where the police were empowered to make a decision (but not required to make an arrest- but must have probable cause).</p>
<p>Each officer carried a pad of color coded report forms. Each time an officer encountered a situation that fit the experimental criteria, they were to take action as indicated by the color coded form (which were assigned by lottery assignment or random). To monitor the consistency of lottery assignment, research staff rode on patrols for a sample of evenings. (read the article below for further details):</p>
<p>See: <a href="https://en.wikipedia.org/wiki/Minneapolis_Domestic_Violence_Experiment" class="uri">https://en.wikipedia.org/wiki/Minneapolis_Domestic_Violence_Experiment</a>– link to the original article is there.</p>
<p>After qualifying a certain case, police officers were provided three randomized approaches that they could use:</p>
<ol style="list-style-type: decimal">
<li>Send abuser away for 8 hours</li>
<li>Advice and mediation of disputes</li>
<li>Make an arrest</li>
</ol>
<p>For purposes of the experiment, we refer to 1 and 2 as the coddling condition. The main outcome of interest was the rate of reoffending (which condition would have higher rates of reoffending: coddling or arrests?).</p>
<pre class="r"><code>x &lt;- rio::import(&#39;http://faculty.missouri.edu/huangf/data/eval/coddled.sav&#39;)
#x$t_random &lt;- factor(x$t_random, labels = c(&#39;pink&#39;,&#39;yellow&#39;,&#39;blue&#39;))
#x$t_random &lt;- factor(x$t_random, labels = c(&#39;arrest&#39;,&#39;advise&#39;,&#39;separate&#39;))
#head(x)
names(x)</code></pre>
<pre><code>##  [1] &quot;t_random&quot;    &quot;z_coddled&quot;   &quot;d_coddled&quot;   &quot;y82&quot;         &quot;q1&quot;         
##  [6] &quot;q2&quot;          &quot;q3&quot;          &quot;mixed&quot;       &quot;s_influence&quot; &quot;anyweapon&quot;  
## [11] &quot;nonwhite&quot;    &quot;fail_z&quot;</code></pre>
<p>Inspect the variables: z_coddled represents the assigned treatment. d_coddled shows if the treatment was actually delivered.</p>
<pre class="r"><code>descr::crosstab(x$z_coddled, x$d_coddled, prop.r = T, plot = F)</code></pre>
<pre><code>##    Cell Contents 
## |-------------------------|
## |                   Count | 
## |             Row Percent | 
## |-------------------------|
## 
## ====================================
##                x$d_coddled
## x$z_coddled        0       1   Total
## ------------------------------------
## 0                91       1      92 
##                98.9%    1.1%   29.3%
## ------------------------------------
## 1                45     177     222 
##                20.3%   79.7%   70.7%
## ------------------------------------
## Total           136     178     314 
## ====================================</code></pre>
<pre class="r"><code>79.7 - 1.1</code></pre>
<pre><code>## [1] 78.6</code></pre>
<p>Based on this, 80% complied with the treatment delivery of coddling when assigned to coddle. On the other hand, 1 out of 92 coddled when assigned to not coddle. More precisely, 78.6% followed treatment assignment. This can also be estimated using OLS.</p>
<pre class="r"><code>assign1 &lt;- (lm(d_coddled ~  z_coddled, data = x))
assign2 &lt;- (lm(d_coddled ~  z_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed, data = x))
summary(assign1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = d_coddled ~ z_coddled, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.79730 -0.01087  0.20270  0.20270  0.98913 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.01087    0.03584   0.303    0.762    
## z_coddled    0.78643    0.04262  18.451   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3438 on 312 degrees of freedom
## Multiple R-squared:  0.5218, Adjusted R-squared:  0.5203 
## F-statistic: 340.4 on 1 and 312 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>summary(assign2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = d_coddled ~ z_coddled + anyweapon + s_influence + 
##     y82 + q1 + q2 + q3 + nonwhite + mixed, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.92651 -0.03539  0.11573  0.21259  0.90118 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.047312   0.068947   0.686   0.4931    
## z_coddled    0.773049   0.042849  18.041   &lt;2e-16 ***
## anyweapon   -0.064339   0.044525  -1.445   0.1495    
## s_influence -0.087523   0.040233  -2.175   0.0304 *  
## y82         -0.036886   0.048734  -0.757   0.4497    
## q1           0.053236   0.073185   0.727   0.4675    
## q2           0.063912   0.058087   1.100   0.2721    
## q3          -0.002788   0.063121  -0.044   0.9648    
## nonwhite     0.024477   0.039752   0.616   0.5385    
## mixed        0.042235   0.045305   0.932   0.3520    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3422 on 304 degrees of freedom
## Multiple R-squared:  0.5382, Adjusted R-squared:  0.5245 
## F-statistic: 39.37 on 9 and 304 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#jtools::export_summs(assign1, assign2)
<p>mean(x$d_coddled) #mean of coddling delivered</code></pre></p>
<pre><code>## [1] 0.566879</code></pre>
<pre class="r"><code>#match this with p. 33</code></pre>
<p>With controls, the compliance rate was 77.3%.</p>
<p>Let’s investigate the outcome, if the suspect was rearrested. On p. 28, this refers to recidivism or “the occurence of post-treatment domestic assault by the same suspect.”</p>
<p>Using simple descriptives:</p>
<pre class="r"><code>descr::crosstab(x$fail_z, x$z_coddled, prop.c = T, plot = F)</code></pre>
<pre><code>##    Cell Contents 
## |-------------------------|
## |                   Count | 
## |          Column Percent | 
## |-------------------------|
## 
## =================================
##             x$z_coddled
## x$fail_z        0       1   Total
## ---------------------------------
## 0             83     175     258 
##             90.2%   78.8%        
## ---------------------------------
## 1              9      47      56 
##              9.8%   21.2%        
## ---------------------------------
## Total         92     222     314 
##             29.3%   70.7%        
## =================================</code></pre>
<p>Using a linear model. Get the same results. The second model allows for the inclusion of covariates. (including a year dummy and quarter dummies).</p>
<pre class="r"><code>itt1 &lt;- lm(fail_z ~  z_coddled, data = x)
itt2 &lt;- lm(fail_z ~  z_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed  , data = x)
#jtools::export_summs(itt1, itt2)
stargazer::stargazer(itt1, itt2, star.cutoffs = c(.05,.01,.001), type = &#39;text&#39;, no.space = T)</code></pre>
<pre><code>## 
## ================================================================
##                                 Dependent variable:             
##                     --------------------------------------------
##                                        fail_z                   
##                             (1)                    (2)          
## ----------------------------------------------------------------
## z_coddled                  0.114*                0.108**        
##                           (0.047)                (0.041)        
## anyweapon                                        -0.004         
##                                                  (0.042)        
## s_influence                                       0.052         
##                                                  (0.038)        
## y82                                             -0.363***       
##                                                  (0.046)        
## q1                                              0.322***        
##                                                  (0.069)        
## q2                                              0.442***        
##                                                  (0.055)        
## q3                                               0.186**        
##                                                  (0.060)        
## nonwhite                                         -0.017         
##                                                  (0.038)        
## mixed                                             0.047         
##                                                  (0.043)        
## Constant                   0.098*                -0.093         
##                           (0.040)                (0.065)        
## ----------------------------------------------------------------
## Observations                314                    314          
## R2                         0.018                  0.307         
## Adjusted R2                0.015                  0.287         
## Residual Std. Error   0.380 (df = 312)      0.324 (df = 304)    
## F Statistic         5.827* (df = 1; 312) 14.970*** (df = 9; 304)
## ================================================================
## Note:                              *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</code></pre>
<pre class="r"><code>#summary(itt1)
#summary(itt2)</code></pre>
<p>The ITT rate is generally more conservative as this factors in noncompliance (10.8% more arrest if coddled). Often reported because this is in actuality what you get on average if a policy is implemented on a large scale basis. Not everyone complies maybe. Coddling is associated with an increase of rearrests by around 11%. This is the Intent to Treat (ITT) effect.</p>
<p>If you just look at the actual treatment delivery (d_coddled), the effect is smaller than it should be. The effect of coddling here is ~ 8.7%.</p>
<pre class="r"><code>t1 &lt;- lm(fail_z ~  d_coddled , data = x)
t2 &lt;- lm(fail_z ~  d_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed , data = x)
stargazer::stargazer(t1, t2, star.cutoffs = c(.05,.01,.001), type = &#39;text&#39;, no.space = T)</code></pre>
<pre><code>## 
## ================================================================
##                                 Dependent variable:             
##                     --------------------------------------------
##                                        fail_z                   
##                             (1)                    (2)          
## ----------------------------------------------------------------
## d_coddled                  0.107*                0.087*         
##                           (0.043)                (0.038)        
## anyweapon                                        -0.002         
##                                                  (0.042)        
## s_influence                                       0.057         
##                                                  (0.038)        
## y82                                             -0.360***       
##                                                  (0.046)        
## q1                                              0.316***        
##                                                  (0.069)        
## q2                                              0.437***        
##                                                  (0.055)        
## q3                                               0.185**        
##                                                  (0.060)        
## nonwhite                                         -0.022         
##                                                  (0.038)        
## mixed                                             0.045         
##                                                  (0.043)        
## Constant                  0.118***               -0.065         
##                           (0.033)                (0.062)        
## ----------------------------------------------------------------
## Observations                314                    314          
## R2                         0.019                  0.303         
## Adjusted R2                0.016                  0.282         
## Residual Std. Error   0.380 (df = 312)      0.325 (df = 304)    
## F Statistic         6.111* (df = 1; 312) 14.683*** (df = 9; 304)
## ================================================================
## Note:                              *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</code></pre>
<p>To ‘recover’ the actual effect, divide the ITT estimate (10.8%) with the compliance rate (77.3%).</p>
<pre class="r"><code>.108/.773</code></pre>
<pre><code>## [1] 0.1397154</code></pre>
<p>The effect is actually a bit higher (14.0%). However, no one really calculates it this way– just shows how this is done. The other way is to run two regressions. In the first regression (or the first stage as it is called), predict actual compliance using treatment assignment (here we use the <code>fitted</code> function). We already did this in the <code>assign2</code> model earlier (to get the compliance rate). Next, we estimate the outcome using the predicted values based on <code>assign2</code>.</p>
<pre class="r"><code>stage1 &lt;- lm(fail_z ~ fitted(assign1), data = x)
stage2 &lt;- lm(fail_z ~ fitted(assign2) + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed, data = x)
stargazer::stargazer(stage1, stage2, star.cutoffs = c(.05,.01,.001), type = &#39;text&#39;, no.space = T)</code></pre>
<pre><code>## 
## ================================================================
##                                 Dependent variable:             
##                     --------------------------------------------
##                                        fail_z                   
##                             (1)                    (2)          
## ----------------------------------------------------------------
## fitted(assign1)            0.145*                               
##                           (0.060)                               
## fitted(assign2)                                  0.140**        
##                                                  (0.052)        
## anyweapon                                         0.005         
##                                                  (0.043)        
## s_influence                                       0.064         
##                                                  (0.039)        
## y82                                             -0.358***       
##                                                  (0.046)        
## q1                                              0.314***        
##                                                  (0.069)        
## q2                                              0.433***        
##                                                  (0.055)        
## q3                                               0.186**        
##                                                  (0.060)        
## nonwhite                                         -0.021         
##                                                  (0.038)        
## mixed                                             0.041         
##                                                  (0.043)        
## Constant                   0.096*                -0.100         
##                           (0.040)                (0.067)        
## ----------------------------------------------------------------
## Observations                314                    314          
## R2                         0.018                  0.307         
## Adjusted R2                0.015                  0.287         
## Residual Std. Error   0.380 (df = 312)      0.324 (df = 304)    
## F Statistic         5.827* (df = 1; 312) 14.970*** (df = 9; 304)
## ================================================================
## Note:                              *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</code></pre>
<p>The point estimate is correct though the standard error (.052) may be off. In general, this is computed using canned functions in statistics programs. In this case though, the standard errors were similar.</p>
<p>The actual IV reg using two stage least squares estimation (2SLS). Can be done using the <code>sem</code> or <code>AER</code> package. Shown both ways below (one with no controls, other with controls).</p>
<pre class="r"><code>iv1 &lt;- sem::tsls(fail_z ~  d_coddled, ~ z_coddled, data = x)
iv2 &lt;- sem::tsls(fail_z ~  d_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed, ~ anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed + z_coddled , data = x)
summary(iv1)</code></pre>
<pre><code>## 
##  2SLS Estimates
## 
## Model Formula: fail_z ~ d_coddled
## 
## Instruments: ~z_coddled
## 
## Residuals:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.24107 -0.24107 -0.09625  0.00000 -0.09625  0.90375 
## 
##               Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) 0.09625202 0.04024964 2.39138 0.017378 *
## d_coddled   0.14481385 0.06003622 2.41211 0.016437 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3807832 on 312 degrees of freedom</code></pre>
<pre class="r"><code>summary(iv2)</code></pre>
<pre><code>## 
##  2SLS Estimates
## 
## Model Formula: fail_z ~ d_coddled + anyweapon + s_influence + y82 + q1 + q2 + 
##     q3 + nonwhite + mixed
## 
## Instruments: ~anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed + 
##     z_coddled
## 
## Residuals:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.55831 -0.20427 -0.04468  0.00000  0.11556  0.97566 
## 
##                 Estimate   Std. Error  t value   Pr(&gt;|t|)    
## (Intercept) -0.099921186  0.066920037 -1.49314  0.1364369    
## d_coddled    0.139898052  0.052777514  2.65071  0.0084529 ** 
## anyweapon    0.004955654  0.042832553  0.11570  0.9079680    
## s_influence  0.064255255  0.038909632  1.65140  0.0996901 .  
## y82         -0.358006623  0.046428421 -7.71094 1.7941e-13 ***
## q1           0.314227128  0.069686777  4.50914 9.3049e-06 ***
## q2           0.433264526  0.055436372  7.81553 9.0150e-14 ***
## q3           0.186213372  0.060104751  3.09815  0.0021293 ** 
## nonwhite    -0.020594117  0.037793842 -0.54491  0.5862172    
## mixed        0.041405215  0.043250600  0.95733  0.3391600    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3258485 on 304 degrees of freedom</code></pre>
<pre class="r"><code>iv1a &lt;- AER::ivreg(fail_z ~ d_coddled | z_coddled, data = x)
iv2a &lt;- AER::ivreg(fail_z ~ d_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed | anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed + z_coddled , data = x)
<p>summary(iv1a)</code></pre></p>
<pre><code>## 
## Call:
## AER::ivreg(formula = fail_z ~ d_coddled | z_coddled, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.24107 -0.24107 -0.09625 -0.09625  0.90375 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  0.09625    0.04025   2.391   0.0174 *
## d_coddled    0.14481    0.06004   2.412   0.0164 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3808 on 312 degrees of freedom
## Multiple R-Squared: 0.01682, Adjusted R-squared: 0.01367 
## Wald test: 5.818 on 1 and 312 DF,  p-value: 0.01644</code></pre>
<pre class="r"><code>summary(iv2a)</code></pre>
<pre><code>## 
## Call:
## AER::ivreg(formula = fail_z ~ d_coddled + anyweapon + s_influence + 
##     y82 + q1 + q2 + q3 + nonwhite + mixed | anyweapon + s_influence + 
##     y82 + q1 + q2 + q3 + nonwhite + mixed + z_coddled, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.55831 -0.20427 -0.04468  0.11556  0.97566 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.099921   0.066920  -1.493  0.13644    
## d_coddled    0.139898   0.052778   2.651  0.00845 ** 
## anyweapon    0.004956   0.042833   0.116  0.90797    
## s_influence  0.064255   0.038910   1.651  0.09969 .  
## y82         -0.358007   0.046428  -7.711 1.79e-13 ***
## q1           0.314227   0.069687   4.509 9.30e-06 ***
## q2           0.433265   0.055436   7.816 9.01e-14 ***
## q3           0.186213   0.060105   3.098  0.00213 ** 
## nonwhite    -0.020594   0.037794  -0.545  0.58622    
## mixed        0.041405   0.043251   0.957  0.33916    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3258 on 304 degrees of freedom
## Multiple R-Squared: 0.2985,  Adjusted R-squared: 0.2777 
## Wald test: 14.79 on 9 and 304 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>library(ivpack)
iv.nocov &lt;- ivreg(fail_z ~ d_coddled | z_coddled, data = x)
summary(iv.nocov)</code></pre>
<pre><code>## 
## Call:
## ivreg(formula = fail_z ~ d_coddled | z_coddled, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.24107 -0.24107 -0.09625 -0.09625  0.90375 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  0.09625    0.04025   2.391   0.0174 *
## d_coddled    0.14481    0.06004   2.412   0.0164 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3808 on 312 degrees of freedom
## Multiple R-Squared: 0.01682, Adjusted R-squared: 0.01367 
## Wald test: 5.818 on 1 and 312 DF,  p-value: 0.01644</code></pre>
<pre class="r"><code>robust.se(iv.nocov)</code></pre>
<pre><code>## [1] &quot;Robust Standard Errors&quot;</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 0.096252   0.031498  3.0558 0.002438 **
## d_coddled   0.144814   0.052694  2.7482 0.006341 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>iv.wcov &lt;- ivreg(fail_z ~ d_coddled + anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed | anyweapon + s_influence + y82 + q1 + q2 + q3 + nonwhite + mixed + z_coddled , data = x)
robust.se(iv.wcov)</code></pre>
<pre><code>## [1] &quot;Robust Standard Errors&quot;</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) -0.0999212  0.0461484 -2.1652 0.0311488 *  
## d_coddled    0.1398981  0.0481670  2.9044 0.0039489 ** 
## anyweapon    0.0049557  0.0420239  0.1179 0.9062053    
## s_influence  0.0642553  0.0369475  1.7391 0.0830302 .  
## y82         -0.3580066  0.0421370 -8.4962 8.879e-16 ***
## q1           0.3142271  0.0537986  5.8408 1.335e-08 ***
## q2           0.4332645  0.0504189  8.5933 4.510e-16 ***
## q3           0.1862134  0.0475390  3.9171 0.0001107 ***
## nonwhite    -0.0205941  0.0367519 -0.5604 0.5756499    
## mixed        0.0414052  0.0415748  0.9959 0.3200808    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><em>BEWARE</em>: Even though the model may look like a strucural equation model (SEM), <em>do not</em> run it like one. Answers will not be the same.</p>
<pre class="r"><code>library(lavaan)
sem1 &lt;- &#39;
fail_z ~ a*d_coddled
d_coddled ~ b*z_coddled
ab := a*b #indirect effect
&#39;
<p>sem1 &lt;- sem(data = x, model = sem1)
summary(sem1)</code></pre></p>
<pre><code>## lavaan (0.6-1.1186) converged normally after  21 iterations
## 
##   Number of observations                           314
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.835
##   Degrees of freedom                                 1
##   P-value (Chi-square)                           0.361
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   fail_z ~                                            
##     d_coddled  (a)    0.107    0.043    2.480    0.013
##   d_coddled ~                                         
##     z_coddled  (b)    0.786    0.042   18.510    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .fail_z            0.144    0.011   12.530    0.000
##    .d_coddled         0.117    0.009   12.530    0.000
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##     ab                0.084    0.034    2.458    0.014</code></pre>
</div>

      </div>

      
  <time class="mt-12 mb-8 block text-xs text-gray-500 ltr:text-right rtl:text-left dark:text-gray-400" datetime="2018-06-27T00:00:00.000Z">
    <span>Last updated on</span>
    Jun 27, 2018</time>

      <div class="container mx-auto prose prose-slate lg:prose-xl dark:prose-invert mt-5">
        
        
  <div id="cusdis_thread"
  data-host="https://cusdis.com"
  data-app-id="999ce0c5-9bf3-489b-a340-698616f5b80a"
  data-page-id="http://localhost:1313/post/iv/"
  data-page-url="http://localhost:1313/post/iv/"
  data-page-title="🎉 Understanding instrumental variables"
  data-theme="auto"
></div>
<script async defer src="https://cusdis.com/js/cusdis.es.js"></script>




      </div>

    </main>
  </article>
</div>

    </div>
    <div class="page-footer">
      <footer class="container mx-auto flex flex-col justify-items-center text-sm leading-6 mt-24 mb-4 text-slate-700 dark:text-slate-200">

  












  
  
  
  
  














  
  
  

  
  
    
  
  
    
  

  

  
  <p class="powered-by text-center">
    © 2025 Grumblesquasher. This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0" rel="noopener noreferrer" target="_blank">CC BY NC SA 4.0</a>
  </p>
  

  <p class="powered-by footer-license-icons">
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0" rel="noopener noreferrer" target="_blank" aria-label="Creative Commons">
      <i class="fab fa-creative-commons fa-2x" aria-hidden="true"></i>
      <i class="fab fa-creative-commons-by fa-2x" aria-hidden="true"></i>
      
        <i class="fab fa-creative-commons-nc fa-2x" aria-hidden="true"></i>
      
      
        <i class="fab fa-creative-commons-sa fa-2x" aria-hidden="true"></i>
      
    </a>
  </p>





  <p class="powered-by text-center">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://hugoblox.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Hugo Blox Builder</a> — the free, <a href="https://github.com/HugoBlox/hugo-blox-builder" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>

</footer>

    </div>

    
    











  </body>
</html>
